### ISSUE TITLE
Unable to load several models.

### ISSUE THREAD

**Issue by naderelzinyvip** [winfordguo/flutter_pytorch_lite#1]
The package architecture didn't allow me to create instances from **FlutterPytorchLite** Class since all its functions are **static**.
I removed static modifier and created two instances since i want to run two models but it show results for the last loaded model only.
Seems like the package allow only one mdoel to be loaded.

**Comment by naderelzinyvip** [comment]
It turned out that mModule stores the last loaded model. I solved it by declaring another load and forward functions.

**Comment by winfordguo** [comment]
It is supported in version  >= [v0.1.0](https://github.com/winfordguo/flutter_pytorch_lite/commit/3f7b37953d08b7f2ba14f56d370906bbc7909660).
